# Generated by Django 4.2.4 on 2024-01-11 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicine', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='medicine',
            old_name='formula',
            new_name='formula_min',
        ),
        migrations.RenameField(
            model_name='type',
            old_name='formula',
            new_name='formula_min',
        ),
        migrations.AddField(
            model_name='medicine',
            name='formula_max',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='type',
            name='formula_max',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
