# Generated by Django 5.0.1 on 2024-01-11 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicine', '0002_rename_formula_medicine_formula_min_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicine',
            name='formula_max',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='medicine',
            name='formula_min',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='type',
            name='formula_max',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='type',
            name='formula_min',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
